require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AnimesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Anime. As you add validations to Anime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attrs = attributes_for :anime
  }

  let(:invalid_attributes) {
    attrs = attributes_for :genre
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnimesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all animes as @animes" do
      animes = Anime.all
      get :index, {}, valid_session
      expect(assigns(:animes).to_json).to eq(animes.to_json)
    end
  end

  describe "GET show" do
    it "assigns the requested anime as @anime" do
      anime = Anime.create! valid_attributes
      get :show, {:id => anime.to_param}, valid_session
      expect(assigns(:anime).first).to eq(anime)
    end
  end

  describe "POST create" do
    it "should create a new anime with Pusher" do

      params = {:anime => valid_attributes}
      get :create, params, valid_session

      anime = assigns(:anime)

      # binding.pry

      expect(anime).to be_an(Anime)
      expect(anime.name).to be_a(String)
      expect(anime.description).to be_a(String)

      expect(anime.errors.size).to  eq(0)
    end

    it "should fail creating a new anime with Pusher" do

      params = {:not_anime => valid_attributes}
      get :create, params, valid_session

      anime = assigns(:anime)
      # binding.pry

      expect(anime.errors.size).to  eq(2)
      puts anime.errors
    end
  end

  describe "PUT update" do
    it "should update an anime with Pusher" do

      id = Anime.first.id;
      attrs = valid_attributes
      attrs[:name] = "Name #{Time.now.to_s}"
      params = {:id => id, :anime => attrs}
      binding.pry
      get :update, params, valid_session

      anime = assigns(:anime)

      # binding.pry

      expect(anime).to be_an(Anime)
      expect(anime.name).to eq(valid_attributes[:name])

      expect(anime.errors.size).to  eq(0)
    end

    it "should fail updating an anime with Pusher" do

      id = Anime.first.id;
      attrs = valid_attributes
      attrs[:name] = nil

      params = {:id => id, :anime => attrs}
      get :update, params, valid_session


      anime = assigns(:anime)

      # binding.pry
      expect(anime.errors.size).not_to  eq(0)
    end
  end


end
