require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NetworksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Network. As you add validations to Network, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attr = attributes_for :network
  }

  let(:invalid_attributes) {
    attrs = attributes_for :genre
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NetworksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all networks as @networks" do
      networks = Network.all
      get :index, {}, valid_session
      expect(assigns(:networks).to_json).to eq(networks.to_json)
    end
  end

  describe "GET show" do
    it "assigns the requested network as @network" do
      network = Network.create! valid_attributes
      get :show, {:id => network.to_param}, valid_session
      expect(assigns(:network).first).to eq(network)
    end
  end

  describe "POST create" do
    it "should create a new network with Pusher" do

      params = {:network => valid_attributes}
      post :create, params, valid_session

      network = assigns(:network)

      # binding.pry

      expect(network).to be_an(Network)
      expect(network.name).to be_a(String)
      expect(network.description).to be_a(String)

      expect(network.errors.size).to  eq(0)
    end

    it "should fail creating a new network with Pusher" do

      params = {:not_network => valid_attributes}
      post :create, params, valid_session

      network = assigns(:network)

      expect(network.errors.size).to_not  eq(0)
      puts network.errors
    end
  end

  describe "PUT update" do
    it "should update an network with Pusher" do

      id = Network.first.id;
      attrs = valid_attributes
      attrs[:name] = "Name #{Time.now.to_s}"
      params = {:id => id, :network => attrs}
      # binding.pry
      put :update, params, valid_session

      network = assigns(:network)

      # binding.pry

      expect(network).to be_an(Network)
      expect(network.name).to eq(valid_attributes[:name])

      expect(network.errors.size).to  eq(0)
    end

    it "should fail updating an network with Pusher" do

      id = Network.first.id;
      attrs = valid_attributes
      attrs[:name] = nil

      params = {:id => id, :network => attrs}
      put :update, params, valid_session


      network = assigns(:network)

      # binding.pry
      expect(network.errors.size).not_to  eq(0)
    end
  end

  describe "DELETE destroy" do
    it "should delete an network with Pusher" do

      network = Network.first

      delete :destroy, {:id => network.id}, valid_session

      expect(network).not_to eq(Network.first)
    end

  end


end
